version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: node

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command:
      ['postgres', '-c', 'log_statement=all', '-c', 'log_destination=stderr']

  cache:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-cache:/data

volumes:
  postgres-data:
  redis-cache:
